---
apiVersion: v1
kind: Service
metadata:
  name: platform-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: platform
  ports:
  - name: platformsvc
    port: 80
    protocol: TCP
    targetPort: 5231
  - name: platformgprc
    port: 666
    protocol: TCP
    targetPort: 666